### PR TITLE
Parallelizing sync cmd

### LINKED ISSUE #100: [FEATURE] improve `sync` command with parallel requests
download/upload/update is running file by file. It is safe to download/upload/update files in parallel requests for better performance.

### PR DESCRIPTION
**Pull request by Roshan-Mehta**
A brief description of the changes in this PR:
Fix https://github.com/0chain/zboxcli/issues/100

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber: https://github.com/0chain/blobber/pull/1037
- gosdk:   https://github.com/0chain/gosdk/pull/909
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by Roshan-Mehta** [comment]
We need to make changes in [gosdk lockBlobber](https://github.com/0chain/gosdk/blob/06cb3d09fffcf297b1fcba3e253ac96858633796/zboxcore/sdk/writemarker_mutex.go#L316) file as well. 
Currently, when we are running multiple goroutines (say for upload), then each upload tries to lock blobber; if it doesn't get the lock, then it sleeps for 2 * timeout.` Hence only one upload is succeeding and others are timing out and we are getting error like 

> unknown_status: Blobber https://demo3.zus.network/blobber01 responded with status 500 and message invalid parameter: requestTime
Error in file operation: lock_consensus_not_met: Required consensus 4 got 0

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-copy  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | test/multi-operation  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | test/multi-operation  |
| gosdk  | feature/multi_operation  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | test/multi-operation  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | feature/parallelizing-sync-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | multi_operation  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
