### PR TITLE
fix(zcncore): used zcncore.MakeSCRestAPICall instead of zboxutil.Make…

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
-

### Fixes
- speed up get info from sharders

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- gosdk: https://github.com/0chain/gosdk/pull/718

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | fix/speed_up_txn_confirm  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/speed_up_txn_confirm  |
| gosdk  | fix/speed_up_txn_confirm  |
| zboxcli  | fix/speed_up_txn_confirm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by boddumanohar — APPROVED** [review]
LGTM

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Pull request merged**
