### PR TITLE
Update README and fixing typo.

### PR DESCRIPTION
**Pull request by vudn95**
#13 
Update README and fixing typo.

### CODE REVIEW

**Comment by stewartie4** [comment]
> #13
> Update README and changing the bellow commands:
> 
> listallocations -> ls-allocations
> newallocation -> alloc-create
> add-collab -> collab-add
> delete-collab -> collab-delete
> update-attributes -> attr-update

These renamed commands are very GNU-like but I can't help feeling like they're now less descriptive and therefore harder to use?
I see this PR brings these commands inline with others such as ls-blobber so happy to approve on that basis

**Comment by guruhubb** [comment]
I agree they are not as descriptive. I think we defer this till later.

**Review by hm90121 — DISMISSED** [review]

**Comment by guruhubb** [comment]
@vudn95 please rollback the changes in the comments and ask to merge

**Comment by vudn95** [comment]
@guruhubb updated PR with rollback comments. Can you please check again?

**Pull request merged**
