### PR TITLE
fix(delete): partial delete should work

### PR DESCRIPTION
**Pull request by cnlangzi**
## Changes
- 
## Fixes
- https://github.com/0chain/gosdk/issues/406

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/626
- system_test: https://github.com/0chain/system_test/pull/234
- zboxcli: https://github.com/0chain/zboxcli/pull/208
- gosdk: https://github.com/0chain/gosdk/pull/427

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/partial-delete-suppport  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/partial-delete-suppport  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Pull request merged**
