### PR TITLE
NFT changes

### LINKED ISSUE #149: NFT changes
Changes outlined in https://github.com/0chain/0chain/issues/828

### PR DESCRIPTION
**Pull request by devyetii**
A brief description of the changes in this PR:
- User can control access to new allocations
- User can see the new fields added to the allocation
- Depend on new gosdk version

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 0chain/0chain#828
- blobber: 0chain/blobber#476
- gosdk: 0chain/gosdk#686
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by devyetii** [comment]
requires 0chain/gosdk#687 to be merged

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 828-nft-restrict-file-access-options  |
| authorizer  | staging  |
| 0box  | 828-nft-restrict-file-access-options  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | staging  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by devyetii** [comment]
@dabasov @peterlimg Kindly review and merge after 0chain/gosdk#687 as it depends on that branch. Unit tests are failing bcz of these dependencies and will be successful when it's merged.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 686-add-fields-to-allocation-to-support-nft  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | true  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by dabasov** [comment]
successful run https://github.com/0chain/0chain/actions/runs/4116598014/jobs/7106843538

**Pull request merged**
