### PR TITLE
issue/524

### PR DESCRIPTION
**Pull request by abouroumine**
zbox required for blobber issue/524.

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber: https://github.com/0chain/blobber/pull/529
- gosdk: https://github.com/0chain/gosdk/pull/416
- system_test: https://github.com/0chain/system_test/pull/218
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by lpoli — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Review by moldis — APPROVED** [review]

**Pull request merged**
