### PR TITLE
New simplified User ReadPool related changes 

### PR DESCRIPTION
**Pull request by iamrz1**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1214
- blobber: https://github.com/0chain/blobber/pull/685
- gosdk: https://github.com/0chain/gosdk/pull/461
- system_test: https://github.com/0chain/system_test/pull/277
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | staging  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | user-read-pools  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | staging  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | user-read-pools  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | user-read-pools  |
| zwalletcli  | staging  |
| 0chain  | user-read-pools  |
| blobber  | user-read-pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
