### PR TITLE
Update gosdk version to fix empty FileID issue

### PR DESCRIPTION
**Pull request by Hitenjain14**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber: https://github.com/0chain/blobber/pull/1069
- gosdk: https://github.com/0chain/gosdk/pull/954
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
