### PR TITLE
update allocation with repair

### LINKED ISSUE #881: pefrom allocation repair on updateallocation  with add/replace blobber
when we add/replace a blobber, we should perform allocation repair so that all the files are synced to the new blobber also

### PR DESCRIPTION
**Pull request by boddumanohar**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/908
- system_test: https://github.com/0chain/system_test/pull/633
- zwalletcli: 
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | update-alloc  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | update-alloc  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | staging  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | staging  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by peterlimg** [comment]
@boddumanohar please resolve conflicts

**Review by Kishan-Dhakan — APPROVED** [review]

**Pull request merged**
