### PR TITLE
fix(merkle): fixed merkle chunk size for challenge hash

### PR DESCRIPTION
**Pull request by cnlangzi**
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- gosdk: https://github.com/0chain/gosdk/pull/370
- blobber: https://github.com/0chain/blobber/pull/533

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zwalletcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| 0chain  | staging  |
| blobber  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zboxcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zboxcli  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/merkle_chunk_size_should_be_fixed_with_64  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by princeparmar — APPROVED** [review]

**Pull request merged**
