### PR TITLE
Fix #182 fixes dead lock

### LINKED ISSUE #182: Zbox cli reaches deadlock on failing to register
Zbox cli is dead locked in bad case scenario. we need to fix this

### PR DESCRIPTION
**Pull request by samtholiya**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:https://github.com/0chain/gosdk/pull/402
- system_test:
- zwalletcli:https://github.com/0chain/zwalletcli/pull/100
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  | fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/registerFailDeadLock  |
| zboxcli  |  fix/deadlock  |
| zwalletcli  | fix/gosdkupdate  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
please update gosdk with latest commit on your branch. it should be 1b3247988866d5615a67ab312bc58a9f58904907

**Comment by cnlangzi** [comment]
latest gosdk has been upgraded on https://github.com/0chain/zboxcli/pull/184.

**Pull request closed without merging**
