### PR TITLE
Enhancement/modify wm for gdpr

### PR DESCRIPTION
**Pull request by lpoli**
A brief description of the changes in this PR:

This PR upgrades gosdk which solves issue https://github.com/0chain/gosdk/issues/570.

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain:   https://github.com/0chain/0chain/pull/1791
- blobber: https://github.com/0chain/blobber/pull/870
- gosdk: https://github.com/0chain/gosdk/pull/637
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm, please resolve the conflicts

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | fix-rounding-off-for-balance  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | enhancement/modify-wm-for-gdpr  |
| gosdk  | enhancement/modify-wm-for-gdpr  |
| zboxcli  | enhancement/modify-wm-for-gdpr  |
| zwalletcli  | staging  |
| 0chain  | enhancement/modify-wm-for-gdpr  |
| blobber  | modify-wm-for-gdpr  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
