### PR TITLE
feat(upload): integrate WriteMarkerMutex on ChunkUpload

### PR DESCRIPTION
**Pull request by cnlangzi**
## Changes
- integrate WriteMarkerMutex on ChunkUpload
## Test
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- zbox: https://github.com/0chain/zboxcli/pull/184
- gosdk: https://github.com/0chain/gosdk/pull/404
- blobber: https://github.com/0chain/blobber/pull/570

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_upload  |
| zboxcli  | feat/integrate_wmlock_on_upload  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/ref_load_root_hash_node  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_upload  |
| zboxcli  | feat/integrate_wmlock_on_upload  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_upload  |
| zboxcli  | feat/integrate_wmlock_on_upload  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/integrate_wmlock_on_upload  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_upload  |
| zboxcli  | feat/integrate_wmlock_on_upload  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/integrate_wmlock_on_upload  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_upload  |
| zboxcli  | feat/integrate_wmlock_on_upload  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
