### PR TITLE
fix(createdir): fixed context issue

### PR DESCRIPTION
**Pull request by lpoli**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/837
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Review by cnlangzi — CHANGES_REQUESTED** [review]
latest commit id is `b2f79bf02c5b47375f97ad257334c13a08bc806e`, please update it. thanks.

**Comment by cnlangzi** [comment]
@lpoli  Could you list related PRs in `Associated PRs (Link as appropriate)` section  in future? It is easier for reviewer to know why gosdk should be upgraded, and which commit id is latest. There are many PRs labelled with `Upgrade gosdk to specific commit` from you. They are confused. 

- https://github.com/0chain/zboxcli/pull/343
- https://github.com/0chain/zboxcli/pull/380
- https://github.com/0chain/zboxcli/pull/375
- https://github.com/0chain/zboxcli/pull/378
- https://github.com/0chain/zboxcli/pull/328
- https://github.com/0chain/zboxcli/pull/322
- .....

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/lock-with-context-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by lpoli** [comment]
> @lpoli Could you list related PRs in `Associated PRs (Link as appropriate)` section in future? It is easier for reviewer to know why gosdk should be upgraded, and which commit id is latest. There are many PRs labelled with `Upgrade gosdk to specific commit` from you. They are confused.
> 
>     * [Upgrade gosdk to specific commit #343](https://github.com/0chain/zboxcli/pull/343)
> 
>     * [Upgrade gosdk to specific commit #380](https://github.com/0chain/zboxcli/pull/380)
> 
>     * [Upgrage gosdk to specific commit #375](https://github.com/0chain/zboxcli/pull/375)
> 
>     * [Upgrade gosdk #378](https://github.com/0chain/zboxcli/pull/378)
> 
>     * [Upgrade gosdk to specific commit #328](https://github.com/0chain/zboxcli/pull/328)
> 
>     * [Upgrade gosdk to specific commit #322](https://github.com/0chain/zboxcli/pull/322)
> 
>     * .....

We can check with the given commit id. 
I see your point though. I will link from next time.
Thanks

**Review by cnlangzi — APPROVED** [review]
LGTM

**Pull request merged**
