### PR TITLE
Added validator option in sp-info

### LINKED ISSUE #297: Updating sp-info to make it generic
Currently, sp-info takes id to be blobber id(Please refer to schema for more details on this one).
This is causing issue in some of the issues desiring id of validator. 
- https://github.com/0chain/system_test/issues/305.
- https://github.com/0chain/system_test/issues/191.

We need to replace it with the generic field ID. For instance replacing ID with `provider_id` and `provider_type` flags.

```
type StakePoolInfo struct {
	ID           string                      `json:"pool_id"`      // pool ID
	Balance      int64                       `json:"balance"`      // total balance
	Unstake      int64                       `json:"unstake"`      // total unstake amount
	Free         int64                       `json:"free"`         // free staked space
	Capacity     int64                       `json:"capacity"`     // blobber bid
	WritePrice   int64                       `json:"write_price"`  // its write price
	OffersTotal  int64                       `json:"offers_total"` //
	UnstakeTotal int64                       `json:"unstake_total"`
	Delegate     []StakePoolDelegatePoolInfo `json:"delegate"`
	Penalty      int64                       `json:"penalty"` // total for all
	Rewards      int64                       `json:"rewards"`
	Settings     StakePoolSettings           `json:"settings"`
}

type StakePoolDelegatePoolInfo struct {
	ID         string `json:"id"`          // blobber ID
	Balance    int64  `json:"balance"`     // current balance
	DelegateID string `json:"delegate_id"` // wallet
	Rewards    int64  `json:"rewards"`     // current
	UnStake    bool   `json:"unstake"`     // want to unstake

	TotalReward  int64  `json:"total_reward"`
	TotalPenalty int64  `json:"total_penalty"`
	Status       string `json:"status"`
	RoundCreated int64  `json:"round_created"`
}
```

### PR DESCRIPTION
**Pull request by iamrz1**
Fixes: https://github.com/0chain/zboxcli/issues/297
Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1733
- gosdk: https://github.com/0chain/gosdk/pull/595

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | generic-sp-info  |
| zwalletcli  | staging  |
| 0chain  | generic-sp-info  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | generic-sp-info  |
| zwalletcli  | staging  |
| 0chain  | generic-sp-info  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by peterlimg** [comment]
@iamrz1 please fix the conflicts

**Review by peterlimg — APPROVED** [review]

**Comment by iamrz1** [comment]
Fixed conflicts. Please remember that this PR depends on changes to go-sdk in the linked PR.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | generic-sp-info  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
