### PR TITLE
Use client ID as stake pool id

### PR DESCRIPTION
**Pull request by peterlimg**
A brief description of the changes in this PR:

## Changes
- Update gosdk and remove `pool_id` param

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1594
- gosdk: https://github.com/0chain/gosdk/pull/556
- system_test: https://github.com/0chain/system_test/pull/380
- zwalletcli: https://github.com/0chain/zwalletcli/pull/172
- loadTest: https://github.com/0chain/loadTest/pull/53

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | staging  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | one-pool  |
| gosdk  | one-pool  |
| zboxcli  | one-pool  |
| zwalletcli  | one-pool  |
| 0chain  | fix/state-hash-mismatch-3  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
