### PR TITLE
Refreshing Documentation

### PR DESCRIPTION
**Pull request by gauryvg98**

### CODE REVIEW

**Review by devyetii — COMMENTED** [review]
Good work, @gauryvg98. Thanks. Just a couple of points left:
- Please add output response example for `alloc-cancel`, `alloc-fini`, `list-all`, `bl-update`, `update`, 
- Please make sure that the command `revoke` works only for --encrypted files as mentioned in the docs.
- Please add example to the `list` command using auth ticket
- Please re-check the `sync` and `get-diff` command by running it locally and make sure it's working as expected. If you already did that, please mention.
- Please hide `add`, `sync`, `get-diff`, `stream`, `get-mpt`, `recent-refs`, `reset-blobber-stats`. Add their existing documentation in README.md to internal.md in the root of the repo.
- Please move streaming documentation from the README file to internal.md
- Ensure the validity of this statement mentioned in the docs: "If the stake pool cannot be unlocked as it would leave insufficient funds for opened offers, then `sp-unlock` tags the stake pool to be unlocked later."
- The command `wp-info` is removed. Please remove all related docs.
- It's mentioned that "`wp-unlock` unlocks an expired write pool." Please verify this statement, that we cannot unlock a write pool for an allocation that's not expired (or cancelled).
- Please add documentation to `createdir`, `decrypt`, `get-mpt`, `list-all`, `rollback`, `validator-update`, `shutdow-blobber`, `shutdown-validator`. For `rollback` I believe you'll need to check the code. Let me know if you need support.

**Comment by devyetii** [comment]
@gauryvg98  Edit for the above comment: please hide `rollback` command and add simple comment on it in the internal.md file.

**Comment by gauryvg98** [comment]
Tested - 
1. command revoke works only for --encrypted files as mentioned in the docs. - working
2. re-check the sync and get-diff - working
3. wp-unlock unlocks an expired write pool." Please verify this statement - expected behavior


Couldn't test : 
1. "If the stake pool cannot be unlocked as it would leave insufficient funds for opened offers, then sp-unlock tags the stake pool to be unlocked later."

2. `bl-update`

**Review by devyetii — APPROVED** [review]
LGTM

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
