### PR TITLE
Fix/update sha1 with sha256 for file hash

### PR DESCRIPTION
**Pull request by cnlangzi**
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [x]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/515
- zwalelet:
- gosdk: https://github.com/0chain/gosdk/pull/363
- 0chain: 
- system_test: https://github.com/0chain/system_test/pull/173

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_remove_issue  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_assertion  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_assertion  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by ssardana96 — APPROVED** [review]

**Comment by ssardana96** [comment]
lgtm

**Pull request merged**
