### PR TITLE
Fix/update attributes

### PR DESCRIPTION
**Pull request by lpoli**
## Changes
Remove whopays attribute

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | fix/update-attributes  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | fix/update-attributes  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | fix/update-attributes  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/update-attributes  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update-attributes  |
| zwalletcli  | fix/update-attributes  |
| 0chain  | staging  |
| blobber  | fix/update-attributes  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
