### PR TITLE
Remove user write pool

### PR DESCRIPTION
**Pull request by Sriep**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1465
- blobber:https://github.com/0chain/blobber/pull/725
- gosdk: https://github.com/0chain/gosdk/pull/490
- system_test: https://github.com/0chain/system_test/pull/315
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by ssardana08 — APPROVED** [review]

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pool  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
